FIELD_CHOICES = (
        ('ROOT FOLDER DATA', 'ROOT FOLDER DATA'),
        ('HIERARCHICAL DATA', 'HIERARCHICAL DATA'),
        ('SEGREGATED DATA', 'SEGREGATED DATA'),
        ('FOLDER DATA', 'FOLDER DATA'),
        ('ANALYSIS DATA', 'ANALYSIS DATA')
    )